version: '3'
services:
  web:
    build: .
    environment:
        - TZ=Asia/Taipei
    ports: 
      - 8085:80
    labels: 
        - "traefik.enable=true"
        - "traefik.basic.frontend.rule=Host:linebotwatchdoctor.liiao.cc"
        - "traefik.frontend.entryPoints=https,http"
    restart: always
    networks:
        - web
  redis:
    image: redis:4-alpine
    command: redis-server --requirepass ${REDIS_PASSWD}
    restart: always
    networks:
      - web
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWD}
    networks:
      - web
networks:
  web:
    external: true