version: '3'
services:
  web:
    build: .
    environment:
        - TZ=Asia/Taipei
    ports: 
      - 8787:80
    restart: always
    depends_on: 
      - redis
  redis:
    image: redis:4-alpine
    command: redis-server --requirepass pwd1234
    ports:
      - 6379:6379

  db:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080